#ifndef CONSTS_H
#define CONSTS_H

#define WORLD_WIDTH 3000
#define WORLD_HEIGHT 1200

#define DEFAULT_WINDOW_WIDTH 1280
#define DEFAULT_WINDOW_HEIGHT 1080

#define PLAYER_FRAME_HEIGHT 100
#define PLAYER_FRAME_WIDTH 40

#define MOVE_SPEED 5
#define JUMP_SPEED 200

#define NUM_BULLETS 100

#endif
