name: CMake Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y cmake build-essential libncurses5-dev libncursesw5-dev
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        make

    - name: Test
      run: |
        cd build
        ctest --verbose
